export default {
    AJAX_UPDATED: 'AJAX_UPDATED',
    AJAX_FAILED: 'AJAX_FAILED',
    BEHAVIORS_CLEANED: 'BEHAVIORS_CLEANED',
    BEHAVIORS_DESTROYED: 'BEHAVIORS_DESTROYED',
    BEHAVIORS_INITIALIZED: 'BEHAVIORS_INITIALIZED',
    POPUP_TRIGGER_CLICKED: 'POPUP_TRIGGER_CLICKED'
};