export default {
    BEHAVIORS_CLEANED: 'BEHAVIORS_CLEANED',
    BEHAVIORS_DESTROYED: 'BEHAVIORS_DESTROYED',
    BEHAVIORS_INITIALIZED: 'BEHAVIORS_INITIALIZED',
    POPUP_TRIGGER_CLICKED: 'POPUP_TRIGGER_CLICKED'
};